-- ■■■■■ CUSTOMER TABLE DAO ■■■■■

-- [1] CHECK DUPLICATES FOR CID 

SELECT *
    FROM CUSTOMER
    WHERE CID = 'aaa';

-- [2] SIGN-UP

INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH)
    VALUES ('ggg', '111', ' 홍마동', '010-1234-1234', 'g@g.com', '서울', 'f', '1995-12-12');
    
-- [3] LOGIN (CID/CPW)

SELECT *
    FROM CUSTOMER
    WHERE CID='aaa'
    AND CPW = '111';

-- [4] CALL DTO USING CID

SELECT *
    FROM CUSTOMER
    WHERE CID='aaa';
    
-- [5] UPDATE CUSTOMER INFO

UPDATE CUSTOMER 
    SET CPW = '111',
    CNAME = '신길동',
    CTEL = '010-9999-8888',
    CEMAIL = 'a@A.COM',
    CADDRESS = '부산',
    CGENDER = 'm',
    CBIRTH = '1990-12-12'
    WHERE CID= 'aaa';

-- [6] PRINT CUSTOMER LIST (IN THE MAIN PAGE)

SELECT *
    FROM (SELECT ROWNUM RN, CID, CPW, CNAME, CEMAIL. CADDRESS
                                    FROM (SELECT * FROM CUSTOMER ORDER BY CID) )
            WHERE RN BETWEEN 4 AND 6;
            
SELECT F.*, CNAME, CEMAIL FROM FILEBOARD F, CUSTOMER C WHERE F.CID=C.CID AND FNUM =2;       
-- [7] COUNT NUMBER OF CUSTOMERS

SELECT COUNT (*) TOTCNT
    FROM BOOK;
    
-- ■■■■■ BOOK TABLE DAO ■■■■■

-- [1] INSERT BOOK
INSERT INTO BOOK (BID, BTITLE, BPRICE, BIMAGE1, BIMAGE2, BCONTENT, BDISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '이것은 자바다', 30000, 'noImg.png','NOTHING.JPG','책설명',20);

-- [2] PRINT BOOK LIST -- NEW BOOKS FIRST

SELECT * FROM BOOK ORDER BY BRDATE DESC;

-- [3] BOOK LIST(top-N구문)

SELECT * 
    FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOOK ORDER BY BRDATE DESC) A)
    WHERE RN BETWEEN 2 AND 3;
    
-- [4] COUNT NUMBER OF BOOKS 

SELECT COUNT(*) CNT FROM BOOK;

-- [5] BOOK DETAIL VIEW(BRING DTO USING BID)

SELECT * FROM BOOK WHERE BID=1;


-- ■■■■■ FILEBOARD TABLE DAO ■■■■■

-- [1] LIST POSTS (startRow - endRow)
SELECT * FROM FILEBOARD;

SELECT * 
    FROM (SELECT ROWNUM RN, A.* 
                        FROM (SELECT F.*, CNAME, CEMAIL 
                                          FROM FILEBOARD F, CUSTOMER C 
                                          WHERE F.CID = C.CID 
                                          ORDER BY FREF DESC, FRE_STEP) A)
        WHERE RN BETWEEN 2 AND 3;
                
-- [2] COUNT NUMBER OF POSTS

SELECT COUNT(*)
    FROM FILEBOARD;

-- [3] WRITE MAIN POST

INSERT INTO FILEBOARD (FNUM,CID, FSUBJECT, FCONTENT, FFILENAME, FPW, FREF, FRE_STEP, FRE_LEVEL, FIP)
    VALUES (FILEBOARD_SEQ.NEXTVAL, 'aaa', '글1', '본문1', null, '111', FILEBOARD_SEQ.CURRVAL, 0, 0, '126.12.12.1');

-- [4] PRE-STEP BEFORE WRITING REPLY POST (step A)
    
    UPDATE FILEBOARD 
        SET FRE_STEP = FRE_STEP+1 
        WHERE FREF=5 
        AND FRE_STEP>0;
    
-- [5] WRITE REPLY POST

INSERT INTO FILEBOARD (FNUM,CID, FSUBJECT, FCONTENT, FFILENAME, FPW, FREF, FRE_STEP, FRE_LEVEL, FIP)
    VALUES (FILEBOARD_SEQ.NEXTVAL, 'bbb', '글1-1', '답', null, '111', 5, 1,1, '192.168.10.10');
    
SELECT *
    FROM FILEBOARD 
    WHERE FREF = 5
    ORDER BY FRE_STEP;
    
-- [6] SEE POST DETAIL

SELECT *
    FROM FILEBOARD 
    WHERE FNUM=5;
    
-- [7] INCREASE VIEW

UPDATE FILEBOARD 
    SET FHIT = FHIT+1 
    WHERE FNUM = 5;
    
-- [8] UPDATE POST

UPDATE FILEBOARD 
    SET FSUBJECT = '수정된 제목',
            FCONTENT = '수정된 본문',
            FFILENAME = NULL,
            FPW = '111',
            FIP = '192.168.10.30'
    WHERE FNUM=1;
    
-- [9] DELETE POST

DELETE FROM FILEBOARD
    WHERE FNUM=1
    AND FPW = '111';
    
COMMIT;
