-- BOOK --

DROP TABLE BOOK CASCADE CONSTRAINTS;

DROP SEQUENCE BOOK_SQ;

CREATE SEQUENCE BOOK_SQ MAXVALUE 99999999 NOCYCLE NOCACHE;

CREATE TABLE BOOK(
    bNUM NUMBER(8) PRIMARY KEY,
    bTITLE VARCHAR2(100) NOT NULL,
    bWRITER VARCHAR2(100) NOT NULL,
    bRDATE DATE DEFAULT SYSDATE NOT NULL,
    bIMG1 VARCHAR2(100) DEFAULT 'noImg.png' NOT NULL,
    bIMG2 VARCHAR2(100) DEFAULT 'noImg.png' NOT NULL,
    bINFO  VARCHAR2(1000)
);

--- MEMBER --

DROP TABLE MEMBER CASCADE CONSTRAINTS;

CREATE TABLE MEMBER(
    mID VARCHAR2(100) PRIMARY KEY,
    mPW VARCHAR2(100) NOT NULL,
    mNAME VARCHAR2(100) NOT NULL,
    mMAIL VARCHAR2(100) NOT NULL,
    mPOST VARCHAR2(100),     -- 우편번호
    mADDR VARCHAR2(100)      -- 주소
);

COMMIT;