-- ¡á¡á¡á¡á¡á GRADE TABLE ¡á¡á¡á¡á¡á --

DROP TABLE GRADE CASCADE CONSTRAINTS;

CREATE TABLE GRADE(
    MGRADE NUMBER(1) PRIMARY KEY,
    GNAME VARCHAR2(30) NOT NULL,
    LOWGRADE NUMBER(9) NOT NULL,
    HIGHGRADE NUMBER(9) NOT NULL);

-- ¡á¡á¡á¡á¡á MEMBER TABLE ¡á¡á¡á¡á¡á --

DROP TABLE MEMBER CASCADE CONSTRAINTS;

CREATE TABLE MEMBER(
    MID VARCHAR2(30) PRIMARY KEY,
    MPW VARCHAR2(30) NOT NULL,
    MNAME VARCHAR2(30) NOT NULL,
    MPHONE VARCHAR(30) NOT NULL,
    MADDRESS VARCHAR2(100),
    MADDRESSDETAIL VARCHAR2(300),
    MBIRTH DATE NOT NULL,
    MEMAIL VARCHAR2(30) NOT NULL,
    MGENDER VARCHAR2(10),
    MCUMPURCHASE NUMBER(9) DEFAULT 0,
    MRDATE DATE DEFAULT SYSDATE,
    MGRADE NUMBER(1) DEFAULT 1 REFERENCES GRADE(MGRADE));
    
select * from product;


-- ¡á¡á¡á¡á¡á BOARD TABLE ¡á¡á¡á¡á¡á --

    DROP TABLE BOARD;
     
    CREATE TABLE BOARD(
        BID NUMBER(6) PRIMARY KEY,
        MID VARCHAR2(30) REFERENCES MEMBER(MID) NOT NULL, 
        BTITLE VARCHAR2(100) NOT NULL,
        BCONTENT CLOB,
        BIMAGE VARCHAR2(30),
        BHIT NUMBER(6) DEFAULT 0 NOT NULL,
        BGROUP NUMBER(6) NOT NULL,
        BSTEP NUMBER(6) DEFAULT 0 NOT NULL,
        BINDENT NUMBER(6) DEFAULT 0 NOT NULL,
        BRDATE DATE DEFAULT SYSDATE,
        ONO NUMBER(6));
    
    DROP SEQUENCE BOARD_SEQ;
     
    CREATE SEQUENCE BOARD_SEQ 
        MAXVALUE 9999999
        NOCACHE
        NOCYCLE;

-- ¡á¡á¡á¡á¡á ORDER TABLE ¡á¡á¡á¡á¡á --

    DROP TABLE ORDERS CASCADE CONSTRAINTS;
    
    CREATE TABLE ORDERS(
        ONO NUMBER(6) PRIMARY KEY,
        ONAME VARCHAR2(30) NOT NULL,
        OPHONE VARCHAR2(30) NOT NULL,
        OADDRESS VARCHAR2(100) NOT NULL,
        OADDRESSDETAIL VARCHAR(500),
        ONOTE VARCHAR2(1000),
        ODATE DATE DEFAULT SYSDATE,
        MID VARCHAR2(30) REFERENCES MEMBER(MID) );
        
    DROP SEQUENCE ORDERNUM_SEQ;
    
    CREATE SEQUENCE ORDERNUM_SEQ
        MAXVALUE 999999
        NOCYCLE
        NOCACHE;    
    
  
                
                
-- ¡á¡á¡á¡á¡á ORDER_DETAIL TABLE ¡á¡á¡á¡á¡á --

    DROP TABLE ORDER_DETAIL CASCADE CONSTRAINTS;
    
    CREATE TABLE ORDER_DETAIL(
        ODNO  NUMBER(6) PRIMARY KEY,
        ONO NUMBER(6)  REFERENCES ORDERS(ONO),
        CARTQUANTITY NUMBER(3),
        PID VARCHAR2(30) NOT NULL REFERENCES PRODUCT(PID));

    DROP SEQUENCE ORDERDETAILNUM_SEQ;

    CREATE SEQUENCE ORDERDETAILNUM_SEQ
        MAXVALUE 999999
        NOCYCLE
        NOCACHE;    
        
        
     
     
-- ¡á¡á¡á¡á¡á PRODUCT TABLE ¡á¡á¡á¡á¡á --
DROP TABLE PRODUCT CASCADE CONSTRAINTS;

CREATE TABLE PRODUCT(
    PID VARCHAR2(30) PRIMARY KEY,
    PNAME VARCHAR2(100) NOT NULL,
    PGROUP NUMBER(2) NOT NULL REFERENCES PRODUCT_GROUP(PGROUP),
    PPRICE NUMBER(9) NOT NULL,
    PDISCOUNT NUMBER(3) DEFAULT 0,
    PIMAGE VARCHAR2(30),
    PSTOCK NUMBER(6) NOT NULL,
    PDESCRIPTION VARCHAR2(1000),
    PRDATE DATE DEFAULT SYSDATE,
    PCUMSALES NUMBER(6) DEFAULT 0,
    PREVIEWCNT NUMBER(6) DEFAULT 0,
    PRATING NUMBER(4,2) DEFAULT 0
    );

DROP SEQUENCE PRODUCT_SEQ;

CREATE SEQUENCE PRODUCT_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;   
    

-- ¡á¡á¡á¡á¡á PRODUCT_GROUP TABLE ¡á¡á¡á¡á¡á --


DROP TABLE PRODUCT_GROUP CASCADE CONSTRAINTS;

 CREATE TABLE PRODUCT_GROUP(
    PGROUP NUMBER(2) PRIMARY KEY NOT NULL,
    PGROUPNAME VARCHAR2(30) NOT NULL,
    PGROUPDESC VARCHAR(400),
    PGROUPIMG VARCHAR2(15));

COMMIT;

-- ¡á¡á¡á¡á¡á PRODUCT REVIEW TABLE ¡á¡á¡á¡á¡á --


DROP TABLE REVIEW CASCADE CONSTRAINTS;

CREATE TABLE REVIEW(
    RNO NUMBER(6) PRIMARY KEY,
    PID VARCHAR2(30) NOT NULL REFERENCES PRODUCT(PID), 
    MID VARCHAR2(30) NOT NULL REFERENCES MEMBER(MID),
    RCONTENT VARCHAR2(2000),
    RIMAGE VARCHAR2(30),
    RSTAR NUMBER(6),
    RRDATE DATE DEFAULT SYSDATE,
    RGROUP NUMBER(6) NOT NULL,
    RSTEP NUMBER(6) DEFAULT 0 NOT NULL,
    RINDENT NUMBER(6) DEFAULT 0 NOT NULL);
    

DROP SEQUENCE REVIEW_SEQ;

CREATE SEQUENCE REVIEW_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;   


-- ¡á¡á¡á¡á¡á CART TABLE ¡á¡á¡á¡á¡á --

DROP TABLE CART;

CREATE TABLE CART(
    CARTNO NUMBER(6) PRIMARY KEY,
    MID VARCHAR2(30) REFERENCES MEMBER(MID),
    PID VARCHAR2(30) REFERENCES PRODUCT(PID),
    CARTQUANTITY NUMBER(3));

DROP SEQUENCE CART_SEQ;

CREATE SEQUENCE CART_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;   

COMMIT;



-- ¡á¡á¡á¡á¡á ADMIN TABLE ¡á¡á¡á¡á¡á --

DROP TABLE ADMIN;

CREATE TABLE ADMIN(
    AID   VARCHAR2(30) PRIMARY KEY,
    APW VARCHAR2(30) NOT NULL,
    ANAME VARCHAR2(30) NOT NULL);
    
SELECT * FROM ADMIN;

COMMIT;

DELETE FROM CART WHERE CARTNO=36;

-- ¡á¡á¡á¡á¡á LOCATION TABLE ¡á¡á¡á¡á¡á --

DROP TABLE LOCATION;

CREATE TABLE LOCATION(
    LID   NUMBER(6) PRIMARY KEY,
    LSTORE VARCHAR(30),
    LADDRESS VARCHAR2(100) NOT NULL);

DROP SEQUENCE LOC_SEQ;

CREATE SEQUENCE LOC_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;   
    
    
    COMMIT;
    
    
    











