-- ■■■■■ GRADE TABLE ■■■■■ --

-- CUSTOMERS ARE CATEGORIZED IN TO 4 GROUPS : NORMAL, GOLD, VIP, VVIP
-- ACCORDING TO GRADE, DISCOUNT RATES DIFFER

INSERT INTO GRADE (MGRADE, GNAME, LOWGRADE, HIGHGRADE)
VALUES (1,'NORMAL',0,1000000);
INSERT INTO GRADE (MGRADE, GNAME, LOWGRADE, HIGHGRADE)
VALUES (2,'GOLD',1000001, 3000000);
INSERT INTO GRADE (MGRADE, GNAME, LOWGRADE, HIGHGRADE)
VALUES (3,'VIP',3000001, 6000000);
INSERT INTO GRADE (MGRADE, GNAME, LOWGRADE, HIGHGRADE)
VALUES (4,'VVIP',6000001,999999999);

select * from grade;
commit;
-- ■■■■■ MEMBER TABLE ■■■■■ --

INSERT INTO MEMBER (MID,MPW,MNAME,MPHONE,MADDRESS,MADDRESSDETAIL,MBIRTH ,MEMAIL,MGENDER) 
    VALUES ('id1','111','이름1','010-1111-2222','주소1','주소2','2017-08-21','one@one/com','남' ); 

INSERT INTO MEMBER (MID,MPW,MNAME,MPHONE,MADDRESS,MADDRESSDETAIL,MBIRTH ,MEMAIL,MGENDER, MCUMPURCHASE, MGRADE) 
    VALUES ('id2','111','이름2','010-1111-2223','주소11','주소22','2000-09-14','two@two.com','여', 0 ,1 ); 
    
INSERT INTO MEMBER (MID,MPW,MNAME,MPHONE,MADDRESS,MADDRESSDETAIL,MBIRTH ,MEMAIL,MGENDER, MCUMPURCHASE, MGRADE) 
    VALUES ('id3','111','이름3','010-1111-2224','주소111','주소222','2001-09-08','three@three.com','남', 1100000 ,2 ); 
    
INSERT INTO MEMBER (MID,MPW,MNAME,MPHONE,MADDRESS,MADDRESSDETAIL,MBIRTH ,MEMAIL,MGENDER, MCUMPURCHASE, MGRADE) 
    VALUES ('id4','111','이름4','010-1111-2225','주소22','주소33','1995-02-17','four@four.com','남', 4300000 ,3 ); 
-- ■■■■■ BOARD TABLE ■■■■■ --

INSERT INTO BOARD (BID, MID, BTITLE, BCONTENT, BIMAGE, BHIT, BGROUP, BSTEP, BINDENT, ONO) 
    VALUES (BOARD_SEQ.NEXTVAL,'id1','이름1','본문1', NULL, 0, BOARD_SEQ.CURRVAL,0, 0 , 2); 
    
INSERT INTO BOARD (BID, MID, BTITLE, BCONTENT, BIMAGE, BHIT, BGROUP, BSTEP, BINDENT, ONO) 
    VALUES (BOARD_SEQ.NEXTVAL,'id2','이름2','본문2', 'gico.jpg', 23, BOARD_SEQ.CURRVAL,0, 0 , 2); 

INSERT INTO BOARD (BID, MID, BTITLE, BCONTENT, BIMAGE, BHIT, BGROUP, BSTEP, BINDENT, ONO) 
    VALUES (BOARD_SEQ.NEXTVAL,'id2','이름2','본문5', 'gico.jpg', 12, BOARD_SEQ.CURRVAL,0, 0 , 2); 
    
INSERT INTO BOARD (BID, MID, BTITLE, BCONTENT, BIMAGE, BHIT, BGROUP, BSTEP, BINDENT, ONO) 
    VALUES (BOARD_SEQ.NEXTVAL,'id4','이름4','본문1', 'gico.jpg', 32, BOARD_SEQ.CURRVAL,0, 0 , 2); 
 
 commit;
-- ■■■■■ ORDER TABLE ■■■■■ --

INSERT INTO ORDERS (ONO, ONAME, OPHONE, OADDRESS, MID)
    VALUES (ORDERNUM_SEQ.NEXTVAL, '이름1', NULL, NULL, 'id1');

COMMIT;

-- ■■■■■ ORDER_DETAIL TABLE ■■■■■ --

INSERT INTO ORDER_DETAIL (ONO, PID, PQUANTITY, PPRICE, TOTCOST, DISCOUNT, PAYAMOUNT)
    VALUES(1, 1 , 2, 20000, 40000, 10,  36000);
    

-- ■■■■■ PRODUCT TABLE ■■■■■ --

INSERT INTO PRODUCT(PID, PNAME, PPRICE, PDISCOUNT, PIMAGE, PSTOCK, PDESCRIPTION, PCUMSALES, PREVIEWCNT, PRATING)
    VALUES ( PRODUCT_SEQ.NEXTVAL , 'SHAMPOO', 20000 , 0, '', 1000, 'This is natural shampoo', 0, 0, 5);
    
 
-- ■■■■■ PRODUCT REVIEW TABLE ■■■■■ --

INSERT INTO REVIEW (RNO, PID, MID, RCONTENT, RIMAGE, RSTAR, RGROUP, RSTEP, RINDENT)
    VALUES(REVIEW_SEQ.NEXTVAL , '1' , 'id1' , '리뷰1', '', 4, REVIEW_SEQ.CURRVAL, 0, 0);


-- ■■■■■ CART TABLE ■■■■■ --

INSERT INTO CART (CARTNO, MID, PID, PCNT)
    VALUES (CART_SEQ.NEXTVAL, 'id1', '1', 1);


-- ■■■■■ ADMIN TABLE ■■■■■ --

INSERT INTO ADMIN (AID, APW, ANAME)
    VALUES('aaa', '111', 'unie');

COMMIT;
