
-- ¡á¡á¡á¡á¡á MEMBER TABLE ¡á¡á¡á¡á¡á

DROP TABLE MEMBER;

CREATE TABLE MEMBER(
    MID VARCHAR2(30) PRIMARY KEY,
    MPW VARCHAR2(30) NOT NULL,
    MNAME VARCHAR2(30) NOT NULL,
    MEMAIL VARCHAR2(30),
    MPHOTO VARCHAR2(30),
    MBIRTH DATE,
    MADDRESS VARCHAR2(300),
    MRDATE DATE DEFAULT SYSDATE);
    
SELECT * FROM MEMBER;

COMMIT;



-- ¡á¡á¡á¡á¡á FILEBOARD TABLE ¡á¡á¡á¡á¡á

DROP TABLE FILEBOARD;

DROP SEQUENCE FILEBOARD_SEQ;


CREATE SEQUENCE FILEBOARD_SEQ 
    MAXVALUE 9999999
    NOCACHE
    NOCYCLE;
    
CREATE TABLE FILEBOARD(
    FID     NUMBER(7) PRIMARY KEY,
    MID      VARCHAR2(50) REFERENCES MEMBER(MID),
    FTITLE VARCHAR2(250) NOT NULL,
    FCONTENT VARCHAR2(4000),
    FFILENAME VARCHAR2(50),
    FRDATE    DATE DEFAULT SYSDATE NOT NULL,
    FHIT      NUMBER(7) DEFAULT 0 NOT NULL,
    FGROUP      NUMBER(7) NOT NULL, --±Û±×·ì
    FSTEP  NUMBER(7) NOT NULL,
    FINDENT NUMBER(7) NOT NULL,
    FIP       VARCHAR2(50) NOT NULL);
    
    
CREATE SEQUENCE FILEBOARD_SEQ 
    MAXVALUE 9999999
    NOCACHE
    NOCYCLE;
    
SELECT * FROM FILEBOARD;

COMMIT;

-- ¡á¡á¡á¡á¡á ADMIN TABLE ¡á¡á¡á¡á¡á


DROP TABLE ADMIN;

CREATE TABLE ADMIN(
    AID   VARCHAR2(30) PRIMARY KEY,
    APW VARCHAR2(30) NOT NULL,
    ANAME VARCHAR2(30) NOT NULL);
    
SELECT * FROM ADMIN;

COMMIT;