-- [VIII] SEQUENCE: Creating Sequential Number, usually to use as a artificial PK

CREATE SEQUENCE FRIEND_SEQ
    START WITH 1 --default
    INCREMENT BY 1  --default
    MAXVALUE 9999 --4자리 까지 할때
    MINVALUE 1 --defualt
    NOCACHE
    NOCYCLE;
    
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL;

--MAKE SEQUENCE--
DROP SEQUENCE FRIEND_SEQ;

CREATE SEQUENCE FRIEND_SEQ --defualt values omitted
    MAXVALUE 9999 --4자리 까지 할때
    NOCACHE --indicate that values of the sequence are not preallocated. (otherwise database caches 20 sequence numbers by default)
    NOCYCLE;

--MAKE TABLE--
DROP TABLE FRIEND;

CREATE TABLE FRIEND (
    NUM NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2 (30) NOT NULL,
    TEL VARCHAR2 (30) UNIQUE,
    ADDRESS VARCHAR2 (300),
    LAST_MODIFYED DATE DEFAULT SYSDATE);
    
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, 'UNIE', '010-7350-0696', 'GANGNAM-GU, SEOUL');
    
 INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, 'CHARLIE', '010-2523-2353', 'YONGSAN-GU, SEOUL');
    
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, 'JIMMY', '010-8645-2356', 'MAPO-GU, SEOUL');
    
    
SELECT * FROM FRIEND;

SELECT FRIEND_SEQ.CURRVAL FROM DUAL;

COMMIT;

--EX01 Create sequence TEST_SEQ with MINVALE of 101, MAXVAUE of 999,999 and increases by 1

CREATE SEQUENCE TEST_SEQ 
    START WITH 101 
    MAXVALUE 999999 
    NOCACHE 
    NOCYCLE;


SELECT TEST_SEQ.
    CURRVAL FROM DUAL; -- ERROR as there is no current value in the subquery
    
SELECT TEST_SEQ.
    NEXTVAL FROM DUAL;




--PRACTICE 1 **TMR TEST


DROP TABLE MEMBER;

DROP SEQUENCE MEMBER_SEQ;

CREATE SEQUENCE MEMBER_SEQ
    MAXVALUE 99
    NOCACHE 
    NOCYCLE;

CREATE TABLE MEMBER(
    MNO VARCHAR2(1) PRIMARY KEY,
    MNAME VARCHAR2(9) NOT NULL,
    MPW VARCHAR(10) CHECK (1<=LENGTH(MPW) AND LENGTH(MPW)<=8),
    MEMAIL VARCHAR(50) UNIQUE,
    MPOINT NUMBER(5) CHECK (0<=MPOINT),
    MRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER (2),
    FOREIGN KEY (LEVELNO) REFERENCES MEMEBER_LEVEL(LEVELNO));


INSERT INTO MEMBER 
    VALUES (MEMBER_SEQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0 , TO_DATE('22/03/10', 'YY/MM//DD'), 0);


INSERT INTO MEMBER 
    VALUES (MEMBER_SEQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 1000, TO_DATE(' 22/04/01', 'YY/MM//DD'), 1);



CREATE TABLE MEMEBER_LEVEL(
    LEVELNO NUMBER (2) PRIMARY KEY,
    LEVELNAME  VARCHAR(10));
 
INSERT INTO MEMEBER_LEVEL 
    VALUES (-1, 'BLACK');

INSERT INTO MEMEBER_LEVEL 
    VALUES (0, '일반');
    
INSERT INTO MEMEBER_LEVEL 
    VALUES (1, '실버');
    
INSERT INTO MEMEBER_LEVEL 
    VALUES (2, '골드');
 
SELECT * FROM MEMBER;
SELECT * FROM MEMEBER_LEVEL;




SELECT * FROM DEPT;

