-- CUS_LEVEL TABLE CONSTRUCTION--
DROP TABLE CUS_LEVEL;

CREATE TABLE CUS_LEVEL(
    LEVELNO NUMBER (1) PRIMARY KEY,
    LEVELNAME  VARCHAR2(10));

INSERT INTO CUS_LEVEL 
    VALUES (1, 'VVIP');
    
INSERT INTO CUS_LEVEL 
    VALUES (2, 'VIP');
    
INSERT INTO CUS_LEVEL 
    VALUES (3, 'NORMAL');
    
INSERT INTO CUS_LEVEL 
    VALUES (4, 'BLACK');

SELECT * 
    FROM CUS_LEVEL;

COMMIT;


-- CUS_LEVEL TABLE CONSTRUCTION--

DROP SEQUENCE CUS_SQ;

CREATE SEQUENCE CUS_SQ
    MAXVALUE 99
    NOCACHE 
    NOCYCLE;

DROP TABLE CUSTOMER;


CREATE TABLE CUSTOMER(
    CNO NUMBER(1) PRIMARY KEY,
    CNAME VARCHAR2(15) NOT NULL,
    JOINDATE DATE DEFAULT SYSDATE,
    PHONE CHAR(13) UNIQUE,
    POINT NUMBER(1),
    LEVELNO NUMBER (1),
    FOREIGN KEY (LEVELNO) REFERENCES CUS_LEVEL(LEVELNO));
    
    
INSERT INTO CUSTOMER 
    VALUES (CUS_SQ.NEXTVAL, '홍길동', TO_DATE('22/03/10', 'YY/MM/DD'), '010-9999-9999', 0, 1);


INSERT INTO CUSTOMER
    VALUES (CUS_SQ.NEXTVAL, '이철수', TO_DATE('22/04/19', 'YY/MM/DD'), '010-8888-8888', NULL, 2);

SELECT * FROM CUSTOMER;
SELECT * FROM CUS_LEVEL;

-- 두 개의 테이블의 내용을 이용하여 아래와 같이 출력되도록 SQL문을 추가 작성한다(15점).

SELECT CNO, CNAME, TO_CHAR(JOINDATE, 'YYYY-mm-dd') JOINDATE, PHONE, POINT, LEVELNAME
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE C.LEVELNO = L.LEVELNO;






