-- STUDENT TABLE CONSTRUCTION

--TABLE STUDENT 
DROP TABLE STUDENT;

CREATE TABLE STUDENT(
    SNO NUMBER(7) PRIMARY KEY,
    SNAME VARCHAR2(15),
    MNO NUMBER(2) REFERENCES MAJOR(MNO),
    SCORE NUMBER(3),
    STATE VARCHAR2(4) DEFAULT 'PASS'); 
    
DROP SEQUENCE STUDENT_NO_SQ;

CREATE SEQUENCE STUDENT_NO_SQ 
    MAXVALUE 99999 
    NOCACHE 
    NOCYCLE;
    
INSERT INTO STUDENT (SNO, SNAME, MNO, SCORE) VALUES (TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_NO_SQ.NEXTVAL,3,'0'), 'ANNA', 4, 98);
INSERT INTO STUDENT (SNO, SNAME, MNO, SCORE) VALUES (TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_NO_SQ.NEXTVAL,3,'0'), 'BEN', 3, 68);
INSERT INTO STUDENT (SNO, SNAME, MNO, SCORE) VALUES (TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_NO_SQ.NEXTVAL,3,'0'), 'CHARLIE', 5, 81);
INSERT INTO STUDENT (SNO, SNAME, MNO, SCORE) VALUES (TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_NO_SQ.NEXTVAL,3,'0'), 'DON', 1, 79);
INSERT INTO STUDENT (SNO, SNAME, MNO, SCORE) VALUES (TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_NO_SQ.NEXTVAL,3,'0'), 'EDDY', 2, 87);
INSERT INTO STUDENT (SNO, SNAME, MNO, SCORE) VALUES (TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_NO_SQ.NEXTVAL,3,'0'), 'FRANK', 1, 94);
INSERT INTO STUDENT (SNO, SNAME, MNO, SCORE) VALUES (TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_NO_SQ.NEXTVAL,3,'0'), 'GREGORIO', 1, 43);
INSERT INTO STUDENT (SNO, SNAME, MNO, SCORE) VALUES (TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_NO_SQ.NEXTVAL,3,'0'), 'HANNA', 2, 88);
INSERT INTO STUDENT (SNO, SNAME, MNO, SCORE) VALUES (TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_NO_SQ.NEXTVAL,3,'0'), 'IZZIE', 1, 100);


--TABLE MAJOR  & SEQUENCE MAJOR

DROP TABLE  MAJOR;
    
CREATE TABLE MAJOR(
    MNO NUMBER(2) PRIMARY KEY,
    MNAME VARCHAR2(30) NOT NULL);

DROP SEQUENCE MAJOR_SQ;

CREATE SEQUENCE MAJOR_SQ 
    MAXVALUE 999 
    NOCACHE 
    NOCYCLE;
    
INSERT INTO MAJOR VALUES (MAJOR_SQ.NEXTVAL,'BIG DATA');
INSERT INTO MAJOR VALUES (MAJOR_SQ.NEXTVAL,'BUSINESS');
INSERT INTO MAJOR VALUES (MAJOR_SQ.NEXTVAL,'COMSCI');
INSERT INTO MAJOR VALUES (MAJOR_SQ.NEXTVAL,'ECONOMICS');
INSERT INTO MAJOR VALUES (MAJOR_SQ.NEXTVAL,'AI STUDIES');


commit;
SELECT * FROM STUDENT;
SELECT * FROM MAJOR;

--[0] Add majors in combo box 



-- [1] 학번검색


SELECT  SNAME, SNO, MNAME, SCORE
    FROM STUDENT S, MAJOR M
    WHERE S.MNO = M.MNO 
    AND S.SNO = '2022001';

-- [2] 이름검색

SELECT SNAME, SNO, MNAME, SCORE
    FROM STUDENT S, MAJOR M
    WHERE S.MNO = M.MNO
    AND SNAME = 'BEN';
    
-- [3] 전공검색  

SELECT ROWNUM RANK, A.*
    FROM (SELECT SNAME ||'('||S.SNO|| ')' SNAME, MNAME||'('||S.MNO||')' MNAME, SCORE, STATE FROM STUDENT S, MAJOR M
            WHERE S.MNO=M.MNO 
            AND MNAME = 'BIG DATA'
            ORDER BY SCORE DESC) A ; 

-- [4] 학생입력  

INSERT INTO STUDENT (SNO, SNAME, MNO, SCORE)
    VALUES ((EXTRACT(YEAR FROM SYSDATE)||LPAD(STUDENT_NO_SQ.NEXTVAL, 3, '0')), 'BOBBY',
            (SELECT MNO FROM MAJOR WHERE MNAME='ECONOMICS'), 99);

-- [5] 학생수정

UPDATE STUDENT 
    SET SNAME =  'DANNY', MNO = (SELECT MNO FROM MAJOR WHERE MNAME='BIG DATA'), SCORE=43
    WHERE SNO = 2022007;

-- [6] 학생출력

SELECT ROWNUM RANK, SNAME, MNAME, SCORE
    FROM (SELECT SNAME||'('||SNO||')' SNAME, MNAME||'('||M.MNO||')' MNAME, SCORE
                FROM STUDENT S, MAJOR M
                WHERE S.MNO=M.MNO AND STATE= 'PASS'
                ORDER BY SCORE DESC);
                
-- [7] 제적처리


UPDATE STUDENT 
    SET STATE =  'FAIL'
    WHERE SNO = 2022003;

-- [8] 제적자출력


SELECT ROWNUM RANK, A.*
    FROM (SELECT SNAME ||'('||S.SNO|| ')' SNAME, MNAME||'('||S.MNO||')' MNAME, SCORE, STATE FROM STUDENT S, MAJOR M
            WHERE S.MNO=M.MNO 
            AND STATE = 'FAIL'
            ORDER BY SCORE DESC) A ; 


SELECT * FROM STUDENT;
SELECT * FROM MAJOR;

DELETE FROM STUDENT WHERE SNAME = 'IZZIE';
DELETE FROM STUDENT WHERE SNAME ='gabby';
DELETE FROM STUDENT WHERE SNAME ='BOB';
COMMIT;

