
--[1] MEMBER --
DROP TABLE MEMBER CASCADE CONSTRAINTS;

CREATE TABLE MEMBER(
    CUSNO NUMBER(5) PRIMARY KEY NOT NULL,
    CUSTNAME VARCHAR2(20),
    PHONE VARCHAR2(20),
    ADDRESS VARCHAR2(20),
    JOINDATE DATE DEFAULT SYSDATE,
    GRADE CHAR(1) REFERENCES GRADE(GRADE),
    CITY CHAR(2));

DROP SEQUENCE MEMBER_SEQ;

CREATE SEQUENCE MEMBER_SEQ MAXVALUE 99999 NOCACHE NOCYCLE;

COMMIT;


--[2] GRADE --
DROP TABLE GRADE CASCADE CONSTRAINTS;

CREATE TABLE GRADE(
    GRADE CHAR(1) PRIMARY KEY,
    GDESC VARCHAR2(20));

COMMIT;


--[3] MONEY --
DROP TABLE MONEY CASCADE CONSTRAINTS;

CREATE TABLE MONEY(
    SALENO NUMBER(6) PRIMARY KEY NOT NULL,
    CUSNO NUMBER(4) NOT NULL REFERENCES MEMBER(CUSNO),
    COST NUMBER(4),
    AMOUNT NUMBER(8),
    PRICE NUMBER(8),
    PCODE VARCHAR2(4),
    SDATE DATE DEFAULT SYSDATE);


DROP SEQUENCE MONEY_SEQ;

CREATE SEQUENCE MONEY_SEQ MAXVALUE 99999 NOCACHE NOCYCLE;

COMMIT;