-- ■■■■■ CUSTOMER TABLE DAO ■■■■■


-- [1] INSERT

INSERT INTO MEMBER (CUSNO, CUSTNAME, PHONE, ADDRESS, JOINDATE, GRADE, CITY) 
    VALUES ('100'||MEMBER_SEQ.NEXTVAL, '정길동', '010-1111-6666', '서울시 용산구', SYSDATE, 'B', '60');
    

-- [2] CALL DTO USING CUSTNO (상세보기)

SELECT *
    FROM MEMBER
    WHERE CUSNO= 1001;
    
SELECT MAX(CUSNO)+1 MAX FROM MEMBER;
    
-- [3] UPDATE (정보수정)
    
UPDATE MEMBER 
    SET CUSTNAME = '최길동',
    PHONE = '010-9999-8888',
    ADDRESS = '부산',
    GRADE = 'C',
    CITY = '60'
    WHERE CUSNO= 1001;

-- [4] PRINT MEMBER LIST (조회)

SELECT * FROM MEMBER 
    ORDER BY CUSNO;

-- [5] 매출조회

    SELECT DISTINCT MEM.CUSNO, MEM.CUSTNAME, GDESC, TOT
        FROM MEMBER MEM, MONEY M, GRADE G, (SELECT CUSNO, SUM(PRICE) TOT FROM MONEY GROUP BY CUSNO) T
        WHERE G.GRADE= MEM.GRADE
        AND MEM.CUSNO = M.CUSNO
        AND T.CUSNO = MEM.CUSNO
        ORDER BY CUSNO;


-- [2] 제품 매출 조회

    SELECT PCODE, SUM(PRICE) TOTSALES 
        FROM MONEY 
        GROUP BY PCODE;
        
        
COMMIT;