DROP SEQUENCE B_SEQ;
DROP TABLE B;
CREATE TABLE B(
    BNO NUMBER(9) PRIMARY KEY,
    BTITLE VARCHAR2(100) NOT NULL,
    BCONTENT CLOB,
    BFILE VARCHAR2(100)
);
CREATE SEQUENCE B_SEQ MAXVALUE 999999999 NOCYCLE NOCACHE;
INSERT INTO B VALUES (B_SEQ.NEXTVAL, '제목1','내용','nothing.jpg');
SELECT * FROM B;
COMMIT;