
-- [1] MEMBER TABLE --
DROP TABLE MEMBER CASCADE CONSTRAINTS;

CREATE TABLE MEMBER(
    MID VARCHAR2(100) PRIMARY KEY,
    MPW VARCHAR2(100) NOT NULL,
    MNAME VARCHAR2(100) NOT NULL,
    MMAIL VARCHAR2(100) NOT NULL,
    MPOST VARCHAR2(100),
    MADDR VARCHAR2(100),
    MTEL VARCHAR(30));


--[2] GROUP TABLE --

DROP SEQUENCE GROUP_SEQ;

CREATE SEQUENCE GROUP_SEQ MAXVALUE 99999999 NOCYCLE NOCACHE;


CREATE TABLE GROUP(
    GID NUMBER(6) PRIMARY KEY,
    GNAME VARCHAR2(30),
    GRDATE DATE NOT NULL,
    GIMG VARCHAR2(50),
    GCONTENT VARCHAR2(4000));
    
-- [3] GROUP DETAIL -- 그룹 맴버 정보

DROP SEQUENCE GROUPDETAIL_SEQ;

CREATE SEQUENCE GROUPDETAIL_SEQ MAXVALUE 99999999 NOCYCLE NOCACHE;
    
CREATE TABLE GROUPDETAIL( -- info about the members in the group
    GDID NUMBER(6) PRIMARY KEY,
    GID NUMBER(6),
    MID VARCHAR2(100),
    GDRDATE DATE NOT NULL, --date member joined
    FOREIGN KEY (GID) REFERENCES GROUP(GID),
    FOREIGN KEY (MID) REFERENCES MEMBER(MID));

-- [4] PAY -- 돈낸 내역들 (예시: 커피 값, 저녁...)

DROP SEQUENCE PAY_SEQ;

CREATE SEQUENCE PAY_SEQ MAXVALUE 99999999 NOCYCLE NOCACHE;

CREATE TABLE PAY(
    PID NUMBER(6) PRIMARY KEY,
    PNAME VARCHAR2(30) NOT NULL,
    PCONTENT VARCHAR(4000),
    PIMAGE VARCHAR2(30),
    PAMOUNT NUMBER(10) NOT NULL,
    PRDATE DATE NOT NULL, -- 결제한 날짜
    GID NUMBER(6) NOT NULL,
    FOREIGN KEY (GID) REFERENCES GROUP(GID)
);

-- [5] PAY DETAIL --  (누가 참여했는지)

DROP SEQUENCE PAYDETAIL_SEQ;

CREATE SEQUENCE PAYDETAIL_SEQ MAXVALUE 99999999 NOCYCLE NOCACHE;

CREATE TABLE PAYDETAIL(
    PDID NUMBER(6) PRIMARY KEY, --UNIQUE KEY
    PID NUMBER(6) NOT NULL, -- DETAIL 정보가 해당되는 결제
    MID VARCHAR2(100)  NOT NULL,
    PDAMOUNT NUMBER(10) NOT NULL, --관련된 사람마다 얼마 내야되는지
    FOREIGN KEY (MID) REFERENCES MEMBER(MID),
    FOREIGN KEY (PID) REFERENCES PAY(PID));

COMMIT;


-- [6] MEMBER DETAIL --  (그룹 내 멤버의 +/-)

DROP SEQUENCE MEMBERDETAIL_SEQ;

CREATE SEQUENCE MEMBERDETAIL_SEQ MAXVALUE 99999999 NOCYCLE NOCACHE;

CREATE TABLE MEMBERDETAIL(
    MDID NUMBER(6) PRIMARY KEY, -- 그룹 내 멤버의 UNIQUE KEY
    MID VARCHAR2(100)  NOT NULL,
    MDCUM NUMBER(10) NOT NULL, -- 그룹 내 멤버 owe amount/ amount to be reimbursed 
    GID NUMBER(6) NOT NULL,
    FOREIGN KEY (GID) REFERENCES GROUP(GID),
    FOREIGN KEY (MID) REFERENCES MEMBER(MID));

COMMIT;







