DROP TABLE FRIEND;

DROP SEQUENCE FRIEND_SQ;

CREATE SEQUENCE   FRIEND_SQ
   MAXVALUE 99999 
    NOCACHE 
    NOCYCLE;
    
    
CREATE TABLE FRIEND(
    FNO NUMBER(2,0) PRIMARY KEY,
    FNAME VARCHAR(20),
    FPHONE VARCHAR(20));
    
SELECT * FROM FRIEND WHERE FPHONE='010-1111-2222';
    
INSERT INTO FRIEND VALUES (FRIEND_SQ.NEXTVAL, '±¸À±¼­', '010-1111-2222');
INSERT INTO FRIEND VALUES (FRIEND_SQ.NEXTVAL, '¹Úµ¿±Ô', '010-2222-3333');
INSERT INTO FRIEND VALUES (FRIEND_SQ.NEXTVAL, '¹ÚÁö¿ø', '010-3333-4444');
INSERT INTO FRIEND VALUES (FRIEND_SQ.NEXTVAL, '±èºó', '010-4444-5555');
INSERT INTO FRIEND VALUES (FRIEND_SQ.NEXTVAL, 'ÃÖÁø¿µ', '010-5555-6666');

COMMIT;

SELECT *
    FROM FRIEND;
    
SELECT * FROM FRIEND WHERE (FNAME LIKE '%'||UPPER('À±')||'%') AND ( FPHONE LIKE '%'||UPPER('12')||'%');
    
DELETE FROM FRIEND WHERE FNAME IS NULL;