DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    ID VARCHAR2(100) PRIMARY KEY,
    PW VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    POSTCODE VARCHAR2(10),
    ADDRESS VARCHAR2(300),
    DETAILADDRESS VARCHAR2(300)
);
-- join
INSERT INTO MEMBER 
    VALUES ('aaa','1','홍길동','06129',
    '서울 강남구 강남대로94길 13 (역삼동)','좋은 빌딩 403호');
-- list
SELECT * FROM MEMBER;
commit;