-- ♂♂♂♂♂ GRADE TABLE ♂♂♂♂♂ --

-- CUSTOMERS ARE CATEGORIZED IN TO 4 GROUPS : NORMAL, GOLD, VIP, VVIP
-- ACCORDING TO GRADE, DISCOUNT RATES DIFFER

INSERT INTO GRADE (MGRADE, GNAME, LOWGRADE, HIGHGRADE)
VALUES (1,'NORMAL',0,1000000);
INSERT INTO GRADE (MGRADE, GNAME, LOWGRADE, HIGHGRADE)
VALUES (2,'GOLD',1000001, 3000000);
INSERT INTO GRADE (MGRADE, GNAME, LOWGRADE, HIGHGRADE)
VALUES (3,'VIP',3000001, 6000000);
INSERT INTO GRADE (MGRADE, GNAME, LOWGRADE, HIGHGRADE)
VALUES (4,'VVIP',6000001,999999999);
 rollback;
-- ♂♂♂♂♂ MEMBER TABLE ♂♂♂♂♂ --

INSERT INTO MEMBER (MID,MPW,MNAME,MPHONE,MADDRESS,MADDRESSDETAIL,MBIRTH ,MEMAIL,MGENDER, MCUMPURCAHSE, MGRADE) 
    VALUES ('id1','111','捞抚1','010-1111-2222','林家1','林家2','2017-08-21','one@one/com','巢', 2500000 ,2 ); 

INSERT INTO MEMBER (MID,MPW,MNAME,MPHONE,MADDRESS,MADDRESSDETAIL,MBIRTH ,MEMAIL,MGENDER, MCUMPURCAHSE, MGRADE) 
    VALUES ('id2','111','捞抚2','010-1111-2223','林家11','林家22','2000-09-14','two@two.com','咯', 0 ,1 ); 
    
INSERT INTO MEMBER (MID,MPW,MNAME,MPHONE,MADDRESS,MADDRESSDETAIL,MBIRTH ,MEMAIL,MGENDER, MCUMPURCAHSE, MGRADE) 
    VALUES ('id3','111','捞抚3','010-1111-2224','林家111','林家222','2001-09-08','three@three.com','巢', 1100000 ,2 ); 
    
INSERT INTO MEMBER (MID,MPW,MNAME,MPHONE,MADDRESS,MADDRESSDETAIL,MBIRTH ,MEMAIL,MGENDER, MCUMPURCAHSE, MGRADE) 
    VALUES ('id4','111','捞抚4','010-1111-2225','林家22','林家33','1995-02-17','four@four.com','巢', 4300000 ,3 ); 
-- ♂♂♂♂♂ BOARD TABLE ♂♂♂♂♂ --

INSERT INTO BOARD (BID, MID, BTITLE, BCONTENT, BIMAGE, BHIT, BGROUP, BSTEP, BINDENT, ONO) 
    VALUES (BOARD_SEQ.NEXTVAL,'id1','捞抚1','夯巩1', NULL, 0, BOARD_SEQ.CURRVAL,0, 0 , 2); 
 
 
-- ♂♂♂♂♂ ORDER TABLE ♂♂♂♂♂ --

INSERT INTO ORDERS (ONO, ONAME, OPHONE, OADDRESS, MID)
    VALUES (ORDERNUM_SEQ.NEXTVAL, '捞抚1', NULL, NULL, 'id1');

COMMIT;

-- ♂♂♂♂♂ ORDER_DETAIL TABLE ♂♂♂♂♂ --

INSERT INTO ORDER_DETAIL (ONO, PID, PQUANTITY, PPRICE, TOTCOST, DISCOUNT, PAYAMOUNT)
    VALUES(1, 1 , 2, 20000, 40000, 10,  36000);
    
    
-- ♂♂♂♂♂ PRODUCT TABLE ♂♂♂♂♂ --

INSERT INTO PRODUCT(PID, PNAME, PPRICE, PDISCOUNT, PIMAGE, PSTOCK, PDESCRIPTION, PCUMSALES, PREVIEWCNT, PRATING)
    VALUES ( PRODUCT_SEQ.NEXTVAL , 'SHAMPOO', 20000 , 0, '', 1000, 'This is natural shampoo', 0, 0, 5);
    
 
-- ♂♂♂♂♂ PRODUCT REVIEW TABLE ♂♂♂♂♂ --

INSERT INTO REVIEW (RNO, PID, MID, RCONTENT, RIMAGE, RSTAR, RGROUP, RSTEP, RINDENT)
    VALUES(REVIEW_SEQ.NEXTVAL , '1' , 'id1' , '府轰1', '', 4, REVIEW_SEQ.CURRVAL, 0, 0);


-- ♂♂♂♂♂ CART TABLE ♂♂♂♂♂ --

INSERT INTO CART (CARTNO, MID, PID, PCNT)
    VALUES (CART_SEQ.NEXTVAL, 'id1', '1', 1);


-- ♂♂♂♂♂ ADMIN TABLE ♂♂♂♂♂ --

INSERT INTO ADMIN (AID, APW, ANAME)
    VALUES('aaa', '111', 'unie');

COMMIT;
